package View;

import DB_Connect.Comunica_Banco;
import Models.Usuarios;
import Models.Paciente;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

public class Janela_Medico extends javax.swing.JFrame {
    
    
    Paciente p = new Paciente(); // instancia o model de pacientes
    Usuarios u = new Usuarios();
    Comunica_Banco db = new Comunica_Banco();
    private Connection con;
    
    public Janela_Medico() {
        initComponents();
    }
    
    
    private void status() {

        try {
            con = db.conectar();
            if (con == null) {
                //System.out.println("Erro de conexão");
                lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dboff.png")));
            } else {
                //System.out.println("Banco conectado");
                lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dbon.png")));
            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        }
    
    private void setarData() {
        Date data = new Date(); // Recebe data do sistema
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL); //responsavel para formatar a data
        lblData.setText(formatador.format(data)); // Altera o texto da Label para a data
    }

    
    private void geraLista() {
        ArrayList<Hospital.Paciente> pct = p.filtraPacientes();
        
        DefaultTableModel tabelaPacientes = (DefaultTableModel) tblPacientes.getModel(); //Traz as caracteristicas da tabela para a variavel
        
        for (Hospital.Paciente paciente : pct) {
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jComboBox1 = new javax.swing.JComboBox<>();
        footer = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        bAcao = new javax.swing.JButton();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        bPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        geraLista1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        bConfig = new javax.swing.JMenu();
        bLogoff = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Misericordia");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Img/5724972_building_healthcare_hospital_medical_nursing_icon.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer.setBackground(new java.awt.Color(0, 255, 255));
        footer.setPreferredSize(new java.awt.Dimension(613, 44));

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dboff.png"))); // NOI18N

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(15, 15, 15))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(16, 16, 16))
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 590, 46));

        bAcao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAcao.setText("Confirmar");
        bAcao.setBorderPainted(false);
        bAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcaoActionPerformed(evt);
            }
        });
        getContentPane().add(bAcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPesquisa.setLabelFor(txtPesquisa);
        lblPesquisa.setText("Pesquisar Paciente por ID:");
        getContentPane().add(lblPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));
        getContentPane().add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 90, 20));

        bPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bPesquisa.setText("Pesquisar");
        bPesquisa.setBorderPainted(false);
        bPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(bPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Paciente", "Tipo de atendimento", "Status", "Ação"
            }
        ));
        jScrollPane1.setViewportView(tblPacientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 590, 190));

        geraLista1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        geraLista1.setText("Atualizar");
        geraLista1.setBorderPainted(false);
        geraLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraLista1ActionPerformed(evt);
            }
        });
        getContentPane().add(geraLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        bConfig.setText("Configurações");

        bLogoff.setText("Logoff");
        bLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoffActionPerformed(evt);
            }
        });
        bConfig.add(bLogoff);

        jMenuBar1.add(bConfig);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.status();
        this.setarData();
    }//GEN-LAST:event_formWindowActivated

    private void bLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoffActionPerformed
        // TODO add your handling code here:
        u.changeStatusOff();
        Janela_Principal jm = new Janela_Principal();
        this.dispose();
        jm.setVisible(true);
    }//GEN-LAST:event_bLogoffActionPerformed

    private void bAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcaoActionPerformed
        // TODO add your handling code here:
        System.out.println(p.filtraPacientes());
    }//GEN-LAST:event_bAcaoActionPerformed

    private void bPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPesquisaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        u.changeStatusOff();
    }//GEN-LAST:event_formWindowClosing

    private void geraLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraLista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geraLista1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Janela_Medico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcao;
    private javax.swing.JMenu bConfig;
    private javax.swing.JMenuItem bLogoff;
    private javax.swing.JButton bPesquisa;
    private javax.swing.JPanel footer;
    private javax.swing.JButton geraLista1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
